"""question table

Revision ID: 8ff5c1585885
Revises: cf134b1c50c2
Create Date: 2020-06-09 12:48:31.906828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff5c1585885'
down_revision = 'cf134b1c50c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('q_text', sa.String(length=256), nullable=True),
    sa.Column('q_var1', sa.String(length=256), nullable=True),
    sa.Column('q_var2', sa.String(length=256), nullable=True),
    sa.Column('q_var3', sa.String(length=256), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
