"""answer table updated

Revision ID: ef32342f0940
Revises: e908f768f5ba
Create Date: 2020-06-11 17:09:01.427410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef32342f0940'
down_revision = 'e908f768f5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('opt_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'opt_id')
    # ### end Alembic commands ###
