"""answers table added

Revision ID: fa6376a3a716
Revises: 8ff5c1585885
Create Date: 2020-06-09 21:36:10.049524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6376a3a716'
down_revision = '8ff5c1585885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('ans_text', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('questions', 'q_var2')
    op.drop_column('questions', 'q_var3')
    op.drop_column('questions', 'q_var1')
    op.drop_column('questions', 'correct')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('correct', sa.INTEGER(), nullable=True))
    op.add_column('questions', sa.Column('q_var1', sa.VARCHAR(length=256), nullable=True))
    op.add_column('questions', sa.Column('q_var3', sa.VARCHAR(length=256), nullable=True))
    op.add_column('questions', sa.Column('q_var2', sa.VARCHAR(length=256), nullable=True))
    op.drop_table('answers')
    # ### end Alembic commands ###
